services:
  postgres:
    image: postgres:17-alpine  # 您可以选择合适的 Postgres 版本, 14 是一个稳定且常用的版本
    container_name: strapi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: strapiuser      # 数据库用户名
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: strapidb          # 数据库名称
    volumes:
      - strapi-data:/var/lib/postgresql/data
    ports:
      - "55543:5432" # 将容器的 5432 端口映射到主机的 5432 端口
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U strapiuser -d strapidb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  strapi-data:
    driver: local
